### ISSUE TITLE
Request to delete feather issue

### ISSUE THREAD

**Issue by ddomhall** [ddomhall/request-to-delete-feather-issue#1]
Hi @colebemis,

I apologise profusely both for this disturbance and for my 15 year old self and ask if there's any chance you can delete the issue linked below?

https://github.com/feathericons/feather/issues/71

My only other option is to create a fresh account as I can't create anything with that on my record.

I apologise again and thank you for your time,
Dom

**Comment by colebemis** [comment]
Sure. I deleted the issue.

**Comment by ddomhall** [comment]
Legend, thank you
